name: 'main'

on:
  push:
    tags:
      - v*
  pull_request:
    types: [ labeled ]

permissions:
  id-token: write
  contents: write

jobs:

  push:
    name: 'Test and Deploy'
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.label.name == 'safe-to-stage'

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:

      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build

      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: test

      - name: Create release version string
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "FLY_RELEASE_VERSION=${GITHUB_REF_NAME:1}" >> $GITHUB_ENV

      - name: Build Zip
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          npm install --global web-ext
          
          # Prepare Files
          cp LICENSE ./dist/
          envsubst < ./extension/manifest.json > ./dist/manifest.json
          envsubst < ./extension/manifest-firefox.json > ./dist/manifest-firefox.json
          cp ./extension/img.png ./dist/img.png
          cd ./dist
          
          # Build Zip for Chrome
          zip -r chrome-extension.zip ./
          mv chrome-extension.zip ../
          
          # Build xpi for firefox
          rm manifest.json
          mv manifest-firefox.json manifest.json
          web-ext sign --api-key=${{secrets.WEB_EXT_API_KEY }} --api-secret=${{ secrets.WEB_EXT_API_SECRET }}
          file=$(ls ./web-ext-artifacts/)
          mv ./web-ext-artifacts/$file ../firefox-extension.xpi
          

      - uses: "marvinpinto/action-automatic-releases@latest"
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            chrome-extension.zip
            firefox-extension.xpi
