name: 'main'

on:
  push:
    tags:
      - v*
  pull_request:
    types: [ labeled ]

permissions:
  id-token: write
  contents: read

jobs:

  push:
    name: 'Test and Deploy'
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.label.name == 'safe-to-stage'

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:

      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.4

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test

      # Checks that all Terraform configuration files adhere to a canonical format
      - name: Terraform Format
        working-directory: terraform
        run: terraform fmt -check

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: "us-east-1"
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: "fly"
          role-duration-seconds: 900

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform plan
        run: terraform plan
        working-directory: terraform

        # On push to main, build or change infrastructure according to Terraform configuration files
        # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
      - name: Terraform Apply
        if: startsWith(github.ref, 'refs/tags/')
        working-directory: terraform
        run: terraform apply -auto-approve

      # Create Cloudfront invalidation
      - run: aws cloudfront create-invalidation --distribution-id E1N3PITIUX8V3S --paths "/*"
        if: startsWith(github.ref, 'refs/tags/')

      - name: Create release version string
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "FLY_RELEASE_VERSION=${GITHUB_REF_NAME:1}" >> $GITHUB_ENV

      - name: Build Zip
        if: startsWith(github.ref, 'refs/tags/')
        run: | 
          cp LICENSE ./dist/
          envsubst < ./extension/manifest.json > ./dist/manifest.json
          cp ./extension/img.png ./dist/img.png
          cd ./dist
          zip -r extension.zip ./
          mv extension.zip ../

      - uses: "marvinpinto/action-automatic-releases@latest"
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            extension.zip
